version: "3"
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data
