version: "3"
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app
      - FLASK_ENV
    volumes:
      - .:/app
    ports:
      - "5000:5000"
