# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AWSMobileClient', '~> 2.12.0'
end

target 'mobile WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile WatchKit App

end

target 'mobile WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile WatchKit Extension

end
